version: '3'
services:
  redis:
    image: "redis:alpine"
  flask_web:
    image: "myregistry.com:5000/flask_demo"
    ports:
      - "5001:5000"
    deploy:
      replicas: 2
    depends_on:
      - redis

    
