version: '3'
services:
  flask_web:
    image: "myregistry.com:5000/flask_demo"
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
    networks:
      - "flask_net"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - /home/docker-service/redis-service/data:/data
    
