version: '3'
services:
  flask_web:
    build: .
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
  redis:
    image: "redis:alpine"
    volumes:
      - /home/docker-service/redis-service/data:/data
    deploy:
      placement:
        constraints: [node.role == worknode]
