mybatis-plus:
  config-location: classpath:mybatis/mybatis_config.xml
  type-aliases-package: com.taoyuanx.demo.business.entity
  mapper-locations: mybatis/mapper/*.xml
  global-config:
    banner: false
    datacenter-id: 1
    worker-id: 1
spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
    dynamic:
      strict: true
      primary: money_a
      datasource:
        money_a:
          url: jdbc:mysql://localhost:3306/money_db_a?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        money_b:
          url: jdbc:mysql://localhost:3306/money_db_b?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&failOverReadOnly=false
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
demo:
  rocketmq:
    name-server-address: 127.0.0.1:9876