version: '3.8'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
    image: "myregistry.com:5000/mysql:5.7.31"
    restart: always
    volumes:
      - "/home/mysql/data:/var/lib/mysql"
      - "/home/mysql/conf:/etc/mysql/conf.d"
      - "/home/mysql/init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    networks:
      - java_net
  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - /home/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - java_net
  bootdemo:
    build:
      context: .
# 执行构建前 执行 export app_version=xxx app_env=xxx
    image: "myregistry.com:5000/springboot_demo_${app_version}:${app_env}"
    volumes:
      - /home/app/:/data
    ports:
      - "8080:8080"
    networks:
      - java_net
    depends_on:
      - mysql
      - redis
  nginx:
    image: "nginx:1.19.1-alpine"
    volumes:
      - /home/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - java_net
    depends_on:
      - bootdemo
networks:
  java_net:
    external:
      name: java_net
