version: '3.8'
services:
  flask_web:
    image: "myregistry.com:5000/flask_demo"
    ports:
      - "5001:5000"
    networks:
      - flask_net2
    deploy:
      replicas: 2
  redis:
    image: "redis:alpine"
    volumes:
      - /home/data:/data
    networks:
      - flask_net2
networks:
  flask_net2:
