version: '3'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
    image: "myregistry.com:5000/mysql:5.7.31"
    restart: always
    volumes:
      - "/home/mysql/data:/var/lib/mysql"
      - "/home/mysql/conf/my.cnf:/etc/my.cnf"
      - "/home/mysql/init:/docker-entrypoint-initdb.d"
      - "/home/mysql/logs:/logs"
    ports:
      - "3306:3306"
    networks:
      - java_net
  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - /home/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - java_net
  springboot_demo:
    image: "myregistry.com:5000/springboot_demo_v1:prod"
    volumes:
      - /home/springboot/logs:/home/logs
    ports:
      - "8080:8080"
    networks:
      - java_net
    depends_on:
      - mysql
      - redis
networks:
  flask_net:
    external:
      name: java_net